Feat: Changing control flow naming to tilde
DataFlowAnalysis/Converter pull request #24
Opened 2024-11-19 23:45 UTC by 01Parzival10

Changing control flow naming to ~ from empty.
Adds additional ~ for multiple incoming control flows to ensure unique names.

2024-11-19 23:55 UTC, 01Parzival10 commented
This fixes the converter side of DataFlowAnalysis/WebEditor#51.
The Editor still needs to be adjusted.

However, I suggest we merge this before the Editor is adjusted. While both the old and new syntax dont get accepted by the Editor, the new at least allows From-PCM-Created-Jsons to be converted into DFD's again

2024-11-26 12:37 UTC, sebinside commented
Needs adjustments from @Kr0nox in the web editor

2024-12-03 12:06 UTC, Nicolas-Boltz commented
@sebinside @Nicolas-Boltz @uuqjz review plz

2024-12-03 12:12 UTC, uuqjz requested changes
Found two things.

2024-12-03 12:12 UTC, uuqjz commented on bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/DataFlowDiagramConverter.java
> +    		String controlFlowName = "" + CONTROL_FLOW_NAME;
Ommit the "" +

2024-12-03 12:12 UTC, uuqjz commented on bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/DataFlowDiagramConverter.java
> +    			controlFlowName += CONTROL_FLOW_NAME;
Why do you store "~", then "~~", "~~~" and so on. I do not understand the purpose.

2024-12-03 13:36 UTC, 01Parzival10 commented on bundles/org.dataflowanalysis.converter/src/org/dataflowanalysis/converter/DataFlowDiagramConverter.java
> +    		String controlFlowName = "" + CONTROL_FLOW_NAME;
Done

2024-12-03 13:47 UTC, uuqjz approved these changes
LGTM

2024-12-09 14:31 UTC, Nicolas-Boltz approved these changes
looks good to me as well

2024-12-09 14:31 UTC, merged